### ISSUE TITLE
When running nothing happens

### ISSUE THREAD

**Issue by janpeeters70** [bramses/summarize-with-gpt3-obsidian#2]
When I run the command 'GPT Summarizer: Summarize' nothing happens/gets output and the console shows.
Anyone else experiencing this? Love to get it to work. 
```
app.js:1 Uncaught (in promise) Error: Request failed, status 429
    at new t (app.js:1:710073)
    at Aw (app.js:1:710265)
    at app.js:1:710942
    at app.js:1:235505
    at Object.next (app.js:1:235610)
    at a (app.js:1:234349)
```

**Comment by bramses** [comment]
If your API key is correct, it may be that your org has sent too many requests:

> ...Rate limit errors ('Too Many Requests', ‘Rate limit reached’) are caused by hitting your organization's [rate limit](https://help.openai.com/en/articles/5955598) which is the maximum number of requests and tokens that can be submitted per minute. If the limit is reached, the organization cannot successfully submit requests until the rate limit is reset.
>
> https://help.openai.com/en/articles/5955604-how-can-i-solve-429-too-many-requests-errors

**Comment by janpeeters70** [comment]
Hi @bramses, API key is filled in correctly. And I'm sure there are not too many requests. I'm the only one using the API key. When I select a piece of English text in Obsidian and run the 'GPT Summarizer: Summarize' nothing happens. I guess I'll have to wait untill someone else runs into this problem and can give more specific details.

**Comment by dxcore35** [comment]
Same problem. Nothing happens!
